name: Android CI

#cada vez que se produsca esta accion
on:
  push:
    branches: [ "ci/cd"]

  pull_request:
    branches: [ "ci/cd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Solicitar permiso para gradle
        run: chmod +x gradlew

      - name: Build app
        run: |
          ./gradlew assembleDebug
        id: Version
        env:
          OUTPUT_FILENAME: ${{ steps.build.outputs.outputFileName }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Display Output File Name
        run: |
          echo "OutputFileName: $OUTPUT_FILENAME"
        shell: bash
      - name: List artifacts APK
        run: ls -la
    
      - uses: actions/upload-artifact@v3
        with: 
          name: app-debug.apk
          path: ./app/build/outputs/apk/debug
