name: Android CI

#cada vez que se produsca esta accion
on:
  push:
    branches: [ "ci/cd"]

  pull_request:
    branches: [ "ci/cd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Solicitar permiso para gradle
        run: chmod +x gradlew

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew assemble
          versionCode=$(grep 'versionCode' app/build.gradle | grep -Eo '[0-9]+')
          versionName=$(grep 'versionName' app/build.gradle | grep -Eo '".*"' | sed 's/"//g')
          baseName=$(grep 'outputFileName' app/build.gradle | grep -Eo '[A-Za-z]+')
          echo "Version Code: $versionCode"
          echo "Version Name: $versionName"
          echo "Base Name: $baseName"
        id: Version
      - name: Generate JSON File
        run: echo '{"outputFileName":"output-metadata.json"}' > output.json
      - name: Display JSON Content
        run: cat output.json
      - name: Read JSON Content and Use Value
        id: read_json
        run: |
          json_content=$(cat output.json)
          outputFileName=$(echo "$json_content" | jq -r '.outputFileName')
          echo "outputFileName: $outputFileName"
        shell: bash
      - name: List artifacts APK
        run: ls -la
    
      - uses: actions/upload-artifact@v3
        with: 
          name: app-debug.apk
          path: ./app/build/outputs/apk/debug
